use serde::{Deserialize, Serialize};
use serde_json;
use std::fs::{read_to_string, write};
use std::path::{Path, PathBuf};

use crate::helpers::{build_cfg_alias_name, compute_file_hash, normalize_hitsound_filename};

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PitchRecord {
    pub filename: String,
    pub content_hash: String,
    pub min_pitch: u32,
    pub max_pitch: u32,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct PitchManifest {
    pub records: Vec<PitchRecord>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PitchSettings {
    pub min_pitch: u32,
    pub max_pitch: u32,
}

pub fn pitch_manifest_path(app_data_dir: &Path) -> PathBuf {
    app_data_dir.join("pitch_manifest.json")
}

pub fn load_pitch_manifest(app_data_dir: &Path) -> PitchManifest {
    let manifest_path = pitch_manifest_path(app_data_dir);
    let manifest_text = read_to_string(manifest_path).unwrap_or_default();

    serde_json::from_str(&manifest_text).unwrap_or_default()
}

pub fn save_pitch_manifest(app_data_dir: &Path, manifest: &PitchManifest) -> Result<(), String> {
    let manifest_path = pitch_manifest_path(app_data_dir);
    let manifest_text = serde_json::to_string_pretty(manifest).map_err(|e| e.to_string())?;
    write(manifest_path, manifest_text).map_err(|e| e.to_string())
}

pub fn find_pitch_record<'a>(manifest: &'a PitchManifest, filename: &str, content_hash: &str) -> Option<&'a PitchRecord> {
    manifest
        .records
        .iter()
        .find(|record| record.filename == filename || record.content_hash == content_hash)
}

pub fn upsert_pitch_record(
    manifest: &mut PitchManifest,
    filename: String,
    content_hash: String,
    min_pitch: u32,
    max_pitch: u32,
) {
    if let Some(record) = manifest
        .records
        .iter_mut()
        .find(|record| record.filename == filename || record.content_hash == content_hash)
    {
        record.filename = filename;
        record.content_hash = content_hash;
        record.min_pitch = min_pitch;
        record.max_pitch = max_pitch;
        return;
    }

    manifest.records.push(PitchRecord {
        filename,
        content_hash,
        min_pitch,
        max_pitch,
    });
}

pub fn remove_pitch_record(manifest: &mut PitchManifest, filename: &str, content_hash: Option<&str>) {
    manifest.records.retain(|record| {
        let filename_match = record.filename == filename;
        let hash_match = content_hash
            .map(|hash| record.content_hash == hash)
            .unwrap_or(false);
        !(filename_match || hash_match)
    });
}

pub fn update_pitch_manifest(
    app_data_dir: &Path,
    manifest: &mut PitchManifest,
    filename: &str,
    min_pitch: u32,
    max_pitch: u32,
) -> Result<(), String> {
    let file_path = app_data_dir.join(filename);
    let content_hash = compute_file_hash(&file_path)?;
    upsert_pitch_record(
        manifest,
        normalize_hitsound_filename(filename),
        content_hash,
        min_pitch,
        max_pitch,
    );
    save_pitch_manifest(app_data_dir, manifest)
}

pub fn get_pitch_settings_for_file(
    app_data_dir: &Path,
    manifest: &PitchManifest,
    filename: &str,
) -> Result<Option<PitchSettings>, String> {
    let file_path = app_data_dir.join(filename);
    let content_hash = compute_file_hash(&file_path)?;

    Ok(find_pitch_record(manifest, filename, &content_hash).map(|record| PitchSettings {
        min_pitch: record.min_pitch,
        max_pitch: record.max_pitch,
    }))
}

pub fn build_hitman_cfg_content(records: &[PitchRecord]) -> String {
    let mut sorted_records = records.to_vec();
    sorted_records.sort_by(|left, right| {
        left.filename
            .cmp(&right.filename)
            .then(left.content_hash.cmp(&right.content_hash))
    });

    let mut content = String::from("// Generated by Hitman\n");

    if sorted_records.is_empty() {
        content.push_str("// No remembered hitsounds yet\n");
        return content;
    }

    for record in sorted_records {
        let alias_name = build_cfg_alias_name(&record.filename);
        content.push_str(&format!(
            concat!(
                "// Hitsound: {filename}\n",
                "alias \"{alias_name}\" \"tf_dingaling_pitchmindmg {min_pitch}; tf_dingaling_pitchmaxdmg {max_pitch}\"\n"
            ),
            filename = record.filename,
            alias_name = alias_name,
            min_pitch = record.min_pitch,
            max_pitch = record.max_pitch
        ));
    }

    content
}
